SELECT COUNT(*) 

FROM [学生考勤表] S 
INNER JOIN COURSES ON LEFT(S.COURSENO,7) = COURSES.COURSENO 
INNER JOIN STUDENTS ON S.STUDENTNO = STUDENTS.STUDENTNO 
INNER JOIN CLASSES ON STUDENTS.CLASSNO = CLASSES.CLASSNO 
left JOIN SCHOOLS ON SCHOOLS.SCHOOL=COURSES.SCHOOL 
left JOIN 学生考勤表请假理由OPTIONS S2 ON S.请假理由 = S2.CODE 
left JOIN TIMESECTORS ON TIMESECTORS.NAME=S.节次 

WHERE S.[YEAR] LIKE :YEAR AND S.TERM LIKE :TERM AND S.STUDENTNO LIKE :STUDENTNO AND S.STUDENTNO IN 
(SELECT STU.STUDENTNO FROM STUDENTS STU WHERE STU.NAME LIKE :NAME) AND 
S.COURSENO LIKE :COURSENO AND S.[周数] LIKE :WEEK AND S.STUDENTNO IN 
(SELECT STU.STUDENTNO FROM STUDENTS STU WHERE STU.SCHOOL LIKE :SCHOOL)