SELECT 

S.ID,S.[YEAR],S.TERM,S.[WEEKS] WEEK,
CONVERT(varchar(10), S.[SCHOOLTIME], 23) DATETIME,
S.SECTORS,
TIMESECTORS.[VALUE] TIMENO,
S.COURSENO,COURSES.COURSENAME,(rtrim(S.COURSENO) + ' / ' + rtrim(COURSES.COURSENAME)) as COURSE,
CLASSES.CLASSNO,CLASSES.CLASSNAME,(rtrim(CLASSES.CLASSNO) + ' / ' + rtrim(CLASSES.CLASSNAME)) as CLASS,
SCHOOLS.NAME SCHOOLNAME,

m1.icount,
m2.icount as icount1,
m3.icount as icount0

FROM courses_class_attendance S 
INNER JOIN COURSES ON LEFT(S.COURSENO,7) = COURSES.COURSENO 
INNER JOIN CLASSES ON S.CLASSNO = CLASSES.CLASSNO 
left JOIN SCHOOLS ON SCHOOLS.SCHOOL=COURSES.SCHOOL 
left JOIN TIMESECTORS ON TIMESECTORS.NAME=S.SECTORS

left join (
select R32.YEAR,R32.TERM,R32.COURSENO,R32.[GROUP],STUDENTS.CLASSNO, count(*) as icount from R32 inner join STUDENTS on STUDENTS.STUDENTNO = R32.STUDENTNO  group by R32.YEAR,R32.TERM,R32.COURSENO,R32.[GROUP],STUDENTS.CLASSNO
) m1 on m1.YEAR = S.YEAR and m1.TERM = S.TERM and m1.COURSENO+m1.[GROUP] = S.COURSENO and m1.CLASSNO = S.CLASSNO

left join (
select COURSES_CLASS_ATTENDANCE_ID, count(*) as icount from [学生考勤表] where [请假理由]='0' group by COURSES_CLASS_ATTENDANCE_ID
) m2 on m2.COURSES_CLASS_ATTENDANCE_ID = S.ID

left join (
select COURSES_CLASS_ATTENDANCE_ID, count(*) as icount from [学生考勤表] where [请假理由] in ('A','B','C') group by COURSES_CLASS_ATTENDANCE_ID
) m3 on m3.COURSES_CLASS_ATTENDANCE_ID = S.ID

WHERE S.ADD_TEACHERNO = :TEACHERNO
AND S.[YEAR] LIKE :YEAR 
AND S.TERM LIKE :TERM 
AND S.COURSENO LIKE :COURSENO
AND CLASSES.CLASSNO LIKE :CLASSNO
AND CLASSES.CLASSNAME LIKE :CLASSNAME
AND S.[WEEKS] LIKE :WEEK
AND CLASSES.SCHOOL LIKE :SCHOOL

ORDER BY S.ID DESC