SELECT COUNT(*) 

FROM courses_class_attendance S 
INNER JOIN COURSES ON LEFT(S.COURSENO,7) = COURSES.COURSENO 
INNER JOIN CLASSES ON S.CLASSNO = CLASSES.CLASSNO 
left JOIN SCHOOLS ON SCHOOLS.SCHOOL=COURSES.SCHOOL 
left JOIN TIMESECTORS ON TIMESECTORS.NAME=S.SECTORS

WHERE S.ADD_TEACHERNO = :TEACHERNO
AND S.[YEAR] LIKE :YEAR 
AND S.TERM LIKE :TERM 
AND S.COURSENO LIKE :COURSENO
AND CLASSES.CLASSNO LIKE :CLASSNO
AND CLASSES.CLASSNAME LIKE :CLASSNAME
AND S.[WEEKS] LIKE :WEEK
AND CLASSES.SCHOOL LIKE :SCHOOL
