CREATE INDEX [FIK_CWEBSCORES_STUDENT] ON [dbo].[cwebs_scores]
([studentno] ASC)
GO

CREATE UNIQUE INDEX [FIK_CWEBSCORES_CGYST] ON [dbo].[cwebs_scores]
([courseno] ASC, [group] ASC, [year] ASC, [studentno] ASC, [term] ASC)
WITH (IGNORE_DUP_KEY = ON)
GO



--20150604--
-- 无清空表
ALTER TABLE [dbo].[R12] ADD [RECNO] int NOT NULL IDENTITY(1,1) ;
ALTER TABLE [dbo].[R12] ALTER COLUMN LIMITGROUPNO int;
--修改teacherplan的teacherno由6位到10位
DROP INDEX [TEACHERPLANMAP] ON [dbo].[TEACHERPLAN]
ALTER TABLE [dbo].[TEACHERPLAN] ALTER COLUMN [TEACHERNO] char(6) COLLATE Chinese_PRC_CI_AS
CREATE INDEX [TEACHERPLANMAP] ON [dbo].[TEACHERPLAN] ([MAP] ASC, [TEACHERNO] ASC)



--20150615--
--教学计划>>添加课程>>课程类别下拉修改为: 必修  限修  通识课程  职业素养、限选
-- delete from COURSETYPEOPTIONS;
-- INSERT INTO [dbo].[COURSETYPEOPTIONS] ([NAME], [VALUE]) VALUES (N'B', N'限修                ');
-- INSERT INTO [dbo].[COURSETYPEOPTIONS] ([NAME], [VALUE]) VALUES (N'A', N'必修                ');
-- INSERT INTO [dbo].[COURSETYPEOPTIONS] ([NAME], [VALUE]) VALUES (N'E', N'限选                ');
-- INSERT INTO [dbo].[COURSETYPEOPTIONS] ([NAME], [VALUE]) VALUES (N'D', N'职业素养            ');
-- INSERT INTO [dbo].[COURSETYPEOPTIONS] ([NAME], [VALUE]) VALUES (N'C', N'通识课程            ');
--教学计划>>课程类别，修改为 公共基础模块，专业特色模块，技能方向模块
DELETE FROM COURSECAT;
INSERT INTO [dbo].[COURSECAT] ([NAME], [VALUE]) VALUES (N'A', N'公共基础模块        ');
INSERT INTO [dbo].[COURSECAT] ([NAME], [VALUE]) VALUES (N'B', N'专业特色模块        ');
INSERT INTO [dbo].[COURSECAT] ([NAME], [VALUE]) VALUES (N'C', N'技能方向模块        ');


--20150617 课程类别 公共基础模块、专业特色模块、技能方向模块、社团课、通识课、职业素养课
DELETE from [COURSETYPEOPTIONS];
INSERT INTO [COURSETYPEOPTIONS] VALUES ('F', '公共基础模块');
INSERT INTO [COURSETYPEOPTIONS] VALUES ('G', '专业特色模块');
INSERT INTO [COURSETYPEOPTIONS] VALUES ('H', '技能方向模块');
INSERT INTO [COURSETYPEOPTIONS] VALUES ('I', '社团课');
INSERT INTO [COURSETYPEOPTIONS] VALUES ('J', '通识课');
INSERT INTO [COURSETYPEOPTIONS] VALUES ('K', '职业素养课');



alter table dbo.CLASSES add REMARK varchar(1000);
alter table dbo.MAJORS add CLASS_NATURE varchar(255);



--20150707
ALTER TABLE [dbo].[COURSEPLAN] ADD [course_type_options] char(1) NOT NULL DEFAULT ''
INSERT INTO METHODS VALUES ('STLK','A','','CoursePlan/Commencement/assoCoursesLook');
INSERT INTO METHODS VALUES ('TSLK','A','','CoursePlan/Commencement/generalCoursesLook');



--20150819 新增三个视图
--VIEW_PROGRAM 代替 VIEWPROGRAMS
SELECT
RTRIM(PROGRAMS.PROGRAMNO) AS PROGRAMNO,
RTRIM(PROGRAMS.PROGNAME)  AS PROGRAMNAME,
PROGRAMS.DATE AS PROGRAMSDATE,
RTRIM(PROGRAMS.REM) AS REM,
RTRIM(PROGRAMS.URL) AS URL,
PROGRAMS.VALID AS VALID,
PROGRAMS.SCHOOL,
PROGRAMS.TYPE as PROGRAMTYPE,
RTRIM(SCHOOLS.NAME) AS SCHOOLNAME,
RTRIM(PROGRAMTYPE.VALUE) AS PROGRAMTYPENAME
FROM PROGRAMS
INNER JOIN SCHOOLS ON PROGRAMS.SCHOOL = SCHOOLS.SCHOOL
INNER JOIN PROGRAMTYPE ON PROGRAMS.TYPE = PROGRAMTYPE.NAME
--VIEW_R28 代替 VIEW_R28
SELECT
RTRIM(PROGRAMS.PROGNAME) AS PROGRAMNO,
RTRIM(PROGRAMS.PROGRAMNO)  AS PROGRAMNAME,
PROGRAMS.DATE AS PROGRAMSDATE,
PROGRAMS.REM AS REM,
PROGRAMS.SCHOOL,
PROGRAMS.TYPE as PROGRAMTYPE,
RTRIM(PROGRAMTYPE.VALUE) AS PROGRAMTYPENAME,
RTRIM(R28.STUDENTNO) AS STUDENTNO,
RTRIM(SCHOOLS.NAME)   AS SCHOOLNAME
FROM R28 INNER JOIN PROGRAMS ON R28.PROGRAMNO = PROGRAMS.PROGRAMNO
INNER JOIN PROGRAMTYPE ON PROGRAMS.TYPE = PROGRAMTYPE.NAME
INNER JOIN SCHOOLS ON PROGRAMS.SCHOOL = SCHOOLS.SCHOOL
--VIEW_LEVEL 代替 LEVEL
SELECT TYPE='全国英语A级成绩',年 as [YEAR],月份 as [MONTH],学院 as [SCHOOL],学号 as STUDENTNO,姓名 as NAME,成绩 as RESULTS,'' as [LEVEL]
	FROM 英语A级统考成绩
UNION ALL
SELECT TYPE='全国英语B级成绩',年 as [YEAR],月份 as [MONTH],学院 as [SCHOOL],学号 as STUDENTNO,姓名 as NAME,成绩 as RESULTS,'' as [LEVEL]
	FROM 英语B级统考成绩
UNION ALL
SELECT TYPE='浙江省计算机等级考试成绩',年 as [YEAR],月份 as [MONTH],学院 as [SCHOOL],学号 as STUDENTNO,姓名 as NAME,成绩 as RESULTS,'' as [LEVEL]
	FROM 计算机统考成绩
UNION ALL
SELECT TYPE='浙江省英语三级成绩',年 as [YEAR],月份 as [MONTH],学院 as [SCHOOL],学号 as STUDENTNO,姓名 as NAME,成绩 as RESULTS,'' as [LEVEL]
	FROM 英语CET3统考成绩
UNION ALL
SELECT TYPE='全国英语四级成绩',年 as [YEAR],月份 as [MONTH],学院 as [SCHOOL],学号 as STUDENTNO,姓名 as NAME,成绩 as RESULTS,'' as [LEVEL]
	FROM 英语CET4统考成绩
UNION ALL
SELECT TYPE='全国英语六级成绩',年 as [YEAR],月份 as [MONTH],学院 as [SCHOOL],学号 as STUDENTNO,姓名 as NAME,成绩 as RESULTS,'' as [LEVEL]
	FROM 英语CET6统考成绩
UNION ALL
SELECT TYPE='浙江省普通话考试成绩',年 as [YEAR],月份 as [MONTH],SCHOOLS.NAME  as [SCHOOL],学号 as STUDENTNO,姓名 as NAME,成绩 as RESULTS,等级 as [LEVEL]
	FROM 普通话等级考试成绩 LEFT JOIN STUDENTS ON STUDENTNO=学号 LEFT JOIN SCHOOLS ON STUDENTS.SCHOOL=SCHOOLS.SCHOOL
UNION ALL
SELECT TYPE='全国大学日语四级成绩',年 as [YEAR],月份 as [MONTH],'' as [SCHOOL],学号 as STUDENTNO,姓名 as NAME,成绩 as RESULTS,'' as [LEVEL]
	FROM 日语CJT4统考成绩


--修改视图VIEWSCHEDULE
--课程类别一的获取从course表变为courseplan表
SELECT DISTINCT
	Dbo_scheduleplan.COURSENO + Dbo_scheduleplan.[GROUP] AS COURSENOGROUP, RTRIM(Dbo_courses.COURSENAME) AS COURSENAME, Dbo_courseplan.CREDITS,
	Dbo_scheduleplan.LHOURS + Dbo_scheduleplan.EHOURS AS WEEKHOURS, Dbo_scheduleplan.EHOURS AS WEEKEXPEHOURS,
	RTRIM(Dbo_courseapproaches.VALUE) AS COURSETYPE, RTRIM(Dbo_examoptions.VALUE) AS EXAMTYPE, RTRIM(Dbo_schools.NAME) AS SCHOOLNAME,
	RTRIM(Dbo_classes.CLASSNAME) AS CLASSNONAME, RTRIM(Dbo_teachers.NAME) + RTRIM(Dbo_positions.VALUE) + '(' + RTRIM(Dbo_taskoptions.NAME)
	+ '课时:' + RTRIM(CONVERT(char(4), Dbo_teacherplan.HOURS)) + RTRIM(Dbo_teacherplan.REM) + ')' AS TEACHERNONAME, RTRIM(Dbo_scheduleplan.REM) AS REM,
	Dbo_scheduleplan.YEAR, Dbo_scheduleplan.TERM, Dbo_scheduleplan.COURSENO, Dbo_scheduleplan.[GROUP], Dbo_courses.SCHOOL, Dbo_courses.TYPE,
	Dbo_courseplan.CLASSNO, Dbo_classes.CLASSNAME, Dbo_teachers.NAME AS TEACHERNAME, Dbo_teachers.TEACHERNO, dbo.SCHEDULE.DAY,
	dbo.SCHEDULE.TIME, dbo.SCHEDULE.ROOMNO, Dbo_scheduleplan.RECNO, Dbo_courseplan.COURSETYPE AS APPROACH, Dbo_courseplan.EXAMTYPE AS EXAM,
	dbo.TIMESECTORS.VALUE, dbo.CLASSROOMS.JSN, '星期' + dbo.SCHEDULE.DAY + RTRIM(dbo.TIMESECTORS.VALUE) + RTRIM(dbo.OEWOPTIONS.NAME)
	+ RTRIM(dbo.CLASSROOMS.JSN) AS DAYNTIME, dbo.SCHEDULE.RECNO AS SCHEDULERECNO, dbo.SCHEDULE.MAP,
	dbo.COURSETYPEOPTIONS.VALUE AS COURSETYPENAME, Dbo_scheduleplan.ESTIMATE, Dbo_scheduleplan.ATTENDENTS, dbo.CLASSROOMS.SEATS,
	dbo.SCHEDULE.OEW, dbo.OEWOPTIONS.NAME, dbo.TIMESECTORS.TIMEBITS, Dbo_teachers.POSITION AS zc,
	Dbo_courseplan.LIMITGROUPNO, Dbo_courseplan.LIMITNUM
FROM         dbo.SCHEDULEPLAN AS Dbo_scheduleplan INNER JOIN
	dbo.COURSES AS Dbo_courses ON Dbo_scheduleplan.COURSENO = Dbo_courses.COURSENO INNER JOIN
	dbo.SCHOOLS AS Dbo_schools ON Dbo_courses.SCHOOL = Dbo_schools.SCHOOL INNER JOIN
	dbo.COURSEPLAN AS Dbo_courseplan ON Dbo_scheduleplan.COURSENO = Dbo_courseplan.COURSENO AND
	Dbo_scheduleplan.[GROUP] = Dbo_courseplan.[GROUP] AND Dbo_scheduleplan.YEAR = Dbo_courseplan.YEAR AND
	Dbo_scheduleplan.TERM = Dbo_courseplan.TERM INNER JOIN
	dbo.CLASSES AS Dbo_classes ON Dbo_courseplan.CLASSNO = Dbo_classes.CLASSNO INNER JOIN
	dbo.COURSEAPPROACHES AS Dbo_courseapproaches ON Dbo_courseplan.COURSETYPE = Dbo_courseapproaches.NAME INNER JOIN
	dbo.EXAMOPTIONS AS Dbo_examoptions ON Dbo_courseplan.EXAMTYPE = Dbo_examoptions.NAME INNER JOIN
--	dbo.COURSETYPEOPTIONS ON Dbo_courses.TYPE = dbo.COURSETYPEOPTIONS.NAME LEFT OUTER JOIN
	dbo.COURSETYPEOPTIONS ON Dbo_courseplan.course_type_options = dbo.COURSETYPEOPTIONS.NAME LEFT OUTER JOIN
	dbo.SCHEDULE ON Dbo_scheduleplan.YEAR = dbo.SCHEDULE.YEAR AND Dbo_scheduleplan.TERM = dbo.SCHEDULE.TERM AND
	Dbo_scheduleplan.COURSENO = dbo.SCHEDULE.COURSENO AND Dbo_scheduleplan.[GROUP] = dbo.SCHEDULE.[GROUP] LEFT OUTER JOIN
	dbo.TIMESECTORS ON dbo.SCHEDULE.TIME = dbo.TIMESECTORS.NAME LEFT OUTER JOIN
	dbo.CLASSROOMS ON dbo.SCHEDULE.ROOMNO = dbo.CLASSROOMS.ROOMNO LEFT OUTER JOIN
	dbo.OEWOPTIONS ON dbo.SCHEDULE.OEW = dbo.OEWOPTIONS.CODE LEFT OUTER JOIN
	dbo.TEACHERPLAN AS Dbo_teacherplan ON Dbo_scheduleplan.RECNO = Dbo_teacherplan.MAP LEFT OUTER JOIN
	dbo.TEACHERS AS Dbo_teachers ON Dbo_teacherplan.TEACHERNO = Dbo_teachers.TEACHERNO LEFT OUTER JOIN
	dbo.TASKOPTIONS AS Dbo_taskoptions ON Dbo_teacherplan.TASK = Dbo_taskoptions.CODE LEFT OUTER JOIN
	dbo.POSITIONS AS Dbo_positions ON Dbo_teachers.POSITION = Dbo_positions.NAME

-- 课程选课情况SQL 代替视图VIEWCOURSESELECTIONSTUDENTS
SELECT
STUDENTS.STUDENTNO as xh, --学号
STUDENTS.NAME as xm,--姓名
SexCode.NAME as xb,--性别
CLASSES.CLASSNAME as xsbj,--班级名称
CLASSES.CLASSNO as bh,--班级号
student_courses.course_choosed_credit_sum as zxf,--学生已选课程的总学分
student_courses.course_choosed_num as xkms,--学生已选课程的门数
R32.CONFLICTS as ct,--冲突
COURSEAPPROACHES.[VALUE] as xkfs,--修课方式
EXAMOPTIONS.[VALUE] as kh2--考核方式
FROM R32
INNER JOIN STUDENTS on R32.STUDENTNO = STUDENTS.STUDENTNO
INNER JOIN CLASSES on CLASSES.CLASSNO = STUDENTS.CLASSNO
INNER JOIN SexCode on STUDENTS.SEX = SexCode.CODE
INNER JOIN COURSEAPPROACHES on R32.APPROACH = COURSEAPPROACHES.NAME
INNER JOIN EXAMOPTIONS on R32.EXAMTYPE = EXAMOPTIONS.NAME
INNER JOIN (
	SELECT
dbo.getone(R32.[GROUP]) as [GROUP] ,
R32.COURSENO,
R32.[YEAR],R32.TERM,R32.STUDENTNO,
count(*) as course_choosed_num ,
sum(COURSEPLAN.CREDITS) as course_choosed_credit_sum
from R32
INNER JOIN COURSEPLAN on R32.[YEAR] = COURSEPLAN.[YEAR] and R32.TERM = COURSEPLAN.TERM and R32.COURSENO = COURSEPLAN.COURSENO
and R32.[GROUP] = COURSEPLAN.[GROUP]
 GROUP BY R32.STUDENTNO,R32.COURSENO,R32.[YEAR],R32.TERM
) student_courses on student_courses.[year] = R32.[YEAR] and student_courses.[term] = R32.[TERM]
	and student_courses.courseno = R32.COURSENO and student_courses.studentno = R32.STUDENTNO
WHERE R32.COURSENO = 'CK2B031' and R32.[GROUP] = '00'
and R32.[YEAR] = 2015 and R32.TERM = 1

--VIEWSCHEDULE 课程类型修改
Dbo_courses.TYPE --改为
Dbo_courseplan.course_type_options as TYPE

--STUDENTS表STATUS字段设置为非null
UPDATE STUDENTS SET STATUS = '' WHERE STATUS is NULL;
UPDATE STUDENTS SET OLDSTUDENTNO = '' WHERE OLDSTUDENTNO is NULL
ALTER TABLE [dbo].[STUDENTS] ALTER COLUMN [OLDSTUDENTNO] char(12) COLLATE Chinese_PRC_CI_AS NOT NULL
ALTER TABLE [dbo].[STUDENTS] ADD DEFAULT '' FOR [OLDSTUDENTNO]

--20150826数据表非空默认处理
ALTER TABLE [dbo].[MAJORS] ADD DEFAULT '' FOR [YEARS]
ALTER TABLE [dbo].[MAJORS] ADD DEFAULT '' FOR [SCHOOL]
ALTER TABLE [dbo].[MAJORS] ADD DEFAULT '' FOR [CLASS_NATURE]
ALTER TABLE [dbo].[MAJORS] ADD DEFAULT '' FOR [CLASS_NATURE_NAME]

--除了key之外，学籍导入不作限制（取消所有的null限制）
ALTER TABLE [dbo].[STUDENTS] ALTER COLUMN [PASSEXPIRED] bit NULL
ALTER TABLE [dbo].[STUDENTS] ALTER COLUMN [lock] bit NULL
ALTER TABLE [dbo].[STUDENTS] ALTER COLUMN [sails] bit NULL
ALTER TABLE [dbo].[STUDENTS] ALTER COLUMN [FREE] bit NULL
ALTER TABLE [dbo].[STUDENTS] ALTER COLUMN [OLDSTUDENTNO] char(12) COLLATE Chinese_PRC_CI_AS NULL

 --旧的学号默认空
ALTER TABLE [dbo].[STUDENTS] ALTER COLUMN [OLDSTUDENTNO] char(12) COLLATE Chinese_PRC_CI_AS NOT NULL
ALTER TABLE [dbo].[STUDENTS] ADD DEFAULT '' FOR [OLDSTUDENTNO]

--SCHEDULE增加限制
ALTER TABLE [dbo].[SCHEDULE] ADD CONSTRAINT [schedule_unique_01] UNIQUE ([YEAR], [TERM], [COURSENO], [GROUP])

--防止删除之后再添加继续删除时提示删除失败  （取消不必要的限制）
ALTER TABLE [dbo].[R32DUMP] DROP CONSTRAINT [PK_R32DUMP]

-- 20160214 将STUDENTS表的classno的长度改为7
ALTER TABLE [dbo].[STUDENTS] ALTER COLUMN [CLASSNO] char(7) COLLATE Chinese_PRC_CI_AS

-- 20160314 删除唯一键约束，老师允许同名
ALTER TABLE [dbo].[TEACHERS] DROP CONSTRAINT [UQ__TEACHERS__D9C1FA002734D139]




