SELECT COUNT(*) 
	FROM COURSEPLAN C LEFT JOIN COURSES C2 ON C.COURSENO=C2.COURSENO 
	LEFT JOIN COURSEAPPROACHES C3 ON C.COURSETYPE=C3.NAME 
	LEFT JOIN CLASSES C4 ON C.CLASSNO=C4.CLASSNO 
	LEFT JOIN SCHOOLS S ON S.SCHOOL=C.SCHOOL 
	LEFT JOIN SCHEDULEPLAN S2 ON C.COURSENO = S2.COURSENO AND C.[GROUP]=S2.[GROUP] AND C.[YEAR]=S2.[YEAR] AND C.TERM=S2.TERM 
WHERE C.[YEAR]=:YEAR AND C.TERM=:TERM AND C3.NAME LIKE :COURSETYPE AND C.COURSENO+C.[GROUP] LIKE :COURSENO AND C2.COURSENAME LIKE :COURSENAME AND C.SCHOOL LIKE :SCHOOL 