INSERT INTO COURSEPLAN
(YEAR,TERM,COURSENO,CLASSNO,SCHOOL,WEEKS,[GROUP],COURSETYPE,EXAMTYPE,ATTENDENTS,REM,LIMITGROUPNO,LIMITNUM,CREDITS,CATEGORY,LIMITRESULT)
VALUES
(:YEAR,:TERM,:COURSENO,:CLASSNO,:SCHOOL,:WEEKS,:GROUP,:COURSETYPE,:EXAMTYPE,:ATTENDENTS,:REM,:LIMITGROUPNO,:LIMITNUM,:CREDITS,:CATEGORY,:LIMITRESULT)