SELECT COUNT(TEACHERPLAN.RECNO) AS ROWS
FROM TEACHERPLAN
inner join TEACHERS on TEACHERPLAN.TEACHERNO=TEACHERS.TEACHERNO
left join UNITOPTIONS on TEACHERPLAN.UNIT=UNITOPTIONS.CODE
left join TASKOPTIONS on TEACHERPLAN.TASK=TASKOPTIONS.CODE
left join SCHOOLS on TEACHERS.SCHOOL=SCHOOLS.SCHOOL
left join ZO on TEACHERPLAN.TOSCHEDULE=CAST(ZO.NAME AS bit)
left join POSITIONS on TEACHERS.POSITION=POSITIONS.NAME
WHERE TEACHERPLAN.MAP=:RECNO