SELECT COUNT(*) AS ROWS
FROM VIEWSCHEDULETABLE
LEFT OUTER JOIN SCHEDULEPLAN ON VIEWSCHEDULETABLE.RECNO=SCHEDULEPLAN.RECNO
LEFT JOIN R32 ON R32.STUDENTNO=:STUDENTNO AND R32.YEAR=VIEWSCHEDULETABLE.YEAR AND R32.TERM = VIEWSCHEDULETABLE.TERM AND R32.COURSENO=VIEWSCHEDULETABLE.COURSENO AND R32.[GROUP]=VIEWSCHEDULETABLE.[GROUP]
WHERE VIEWSCHEDULETABLE.YEAR= :YEAR
AND VIEWSCHEDULETABLE.TERM= :TERM
AND VIEWSCHEDULETABLE.COURSENOGROUP LIKE :COURSENOGROUP
AND VIEWSCHEDULETABLE.COURSENAME LIKE :COURSENAME
AND (VIEWSCHEDULETABLE.TEACHERNAME LIKE :TEACHERNAME  OR VIEWSCHEDULETABLE.TEACHERNAME IS NULL)
AND VIEWSCHEDULETABLE.TYPE LIKE :COURSETYPE
AND VIEWSCHEDULETABLE.SCHOOL LIKE :SCHOOL
AND VIEWSCHEDULETABLE.CLASSNO LIKE :CLASSNO
AND (VIEWSCHEDULETABLE.DAY LIKE :DAY OR VIEWSCHEDULETABLE.DAY IS NULL)
AND (VIEWSCHEDULETABLE.TIME LIKE :TIME OR VIEWSCHEDULETABLE.TIME IS NULL)
GROUP BY COURSENOGROUP
