SELECT COUNT(MAJORS.MAJORNO) AS ROWSID
FROM MAJORPLAN 
INNER JOIN MAJORS ON MAJORPLAN.MAP = MAJORS.ROWID 
INNER JOIN MAJORCODE ON MAJORS.MAJORNO = MAJORCODE.CODE 
left JOIN BRANCHCODE ON MAJORS.BRANCH = BRANCHCODE.CODE 
left JOIN DEGREEOPTIONS ON MAJORS.DEGREE = DEGREEOPTIONS.CODE 
left JOIN SCHOOLS ON MAJORS.SCHOOL = SCHOOLS.SCHOOL
WHERE MAJORS.SCHOOL LIKE (:SCHOOL) 
AND MAJORPLAN.YEAR = (:GRADE) 
AND MAJORS.YEARS LIKE (:YEARS) 
AND (isnull(rtrim(MAJORS.MAJORNO),'') + '-' + isnull(cast(MAJORS.CLASS_NATURE as varchar),'')) like :MAJORROWNO   
AND MAJORS.MAJORNO LIKE :MAJOR