select * from (SELECT row_number() over(order by MAJORS.MAJORNO) as row,MAJORS.MAJORNO, MAJORS.YEARS AS MAJORSYEARS, MAJORS.REM AS MAJORSREM,
      MAJORPLAN.YEAR, MAJORPLAN.REM AS MAJORPLANREM, 
      MAJORCODE.NAME AS MAJORCODENAME, BRANCHCODE.NAME AS BRANCHCODENAME, 
      DEGREEOPTIONS.NAME AS DEGREEOPTIONSNAME, SCHOOLS.NAME AS SCHOOLSNAME, 
      MAJORPLAN.MCREDITS AS MAJORPLANMCREDITS, MAJORPLAN.CREDITS AS MAJORPLANCREDITS, 
      MAJORPLAN.专业方向 AS SPECIALS, MAJORPLAN.ROWID AS majorplanrowid,
      (isnull(rtrim(MAJORS.MAJORNO),'') + '-' + isnull(cast(MAJORS.CLASS_NATURE as varchar),'')) as MAJORROWNO,
      MAJORS.ROWID AS majorsrowid, MAJORS.SCHOOL AS school
FROM MAJORPLAN 
INNER JOIN MAJORS ON MAJORPLAN.MAP = MAJORS.ROWID 
INNER JOIN MAJORCODE ON MAJORS.MAJORNO = MAJORCODE.CODE 
left JOIN BRANCHCODE ON MAJORS.BRANCH = BRANCHCODE.CODE 
left JOIN DEGREEOPTIONS ON MAJORS.DEGREE = DEGREEOPTIONS.CODE 
left JOIN SCHOOLS ON MAJORS.SCHOOL = SCHOOLS.SCHOOL
WHERE MAJORS.SCHOOL LIKE (:SCHOOL) 
AND MAJORPLAN.YEAR = (:GRADE) 
AND MAJORS.YEARS LIKE (:YEARS)
AND (isnull(rtrim(MAJORS.MAJORNO),'') + '-' + isnull(cast(MAJORS.CLASS_NATURE as varchar),'')) like :MAJORROWNO   
AND MAJORS.MAJORNO LIKE :MAJOR
) as b where b.row between :start and :end