SELECT TEACHERS.SCHOOL,TEACHERS.TGROUP,USERS.USERNAME,USERS.ROLES,SCHOOLS.NAME AS SCHOOLNAME,S1.NAME AS TGROUPNAME FROM TEACHERS
JOIN USERS ON TEACHERS.TEACHERNO=USERS.TEACHERNO
JOIN SESSIONS ON USERS.USERNAME=SESSIONS.USERNAME
left join SCHOOLS on SCHOOLS.SCHOOL=TEACHERS.SCHOOL
left join SCHOOLS S1 on S1.SCHOOL=TEACHERS.TGROUP
WHERE SESSIONS.SESSIONID=:SESSIONID